name: Tests - relay-service

on:
  push:
    branches-ignore:
      - "main"
      - "staging"
      - "hotfix/**"
      - "release/**"
    paths:
      - "relay-service/**"
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    name: Run Pytest for base agent
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: relay-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Clone py-libp2p relay branch
        run: |
          git clone --branch feat/587-circuit-relay https://github.com/Winter-Soren/py-libp2p.git ../py-libp2p

      - name: Install dependencies
        run: poetry install

      - name: Install py-libp2p fork (inside Poetry env)
        run: poetry run pip install -e ../py-libp2p

      - name: Run tests via Makefile    
        run: poetry run make test
